spring:
  application:
    name: springboot-dubbo-provider

dubbo:
  application: ${spring.application.name}
  scan:
    base-packages: me.jianghs.springbootdubbo.provider.service.impl
  protocol:
    name: dubbo
    port: 12345
  registry:
    address: zookeeper://139.196.190.46:2181
    timeout: 60000
  config-center:
    timeout: 60000